#!/bin/bash
# .SYNOPSIS
# Remediation Script for STIG ID: RHEL-09-213060 This script is created to Disable Stream Control Transmission Protocol (SCTP)
# Author: Reginald D on 11-02-2025
# Description: This script ensures the SCTP kernel module is disabled to reduce the system's attack surface.
# SCTP is rarely used in standard environments and poses security risks if left enabled
# It enforces the required DoD STIG configuration by blacklisting and preventing the SCTP module from loading.
# .USAGE
# sudo ./RHEL-09-213060.sh

[ "$(id -u)" -eq 0 ] || { echo "run as root"; exit 1; }
CONF="/etc/modprobe.d/sctp.conf"
mkdir -p /etc/modprobe.d
echo -e "install sctp /bin/false\nblacklist sctp" > "$CONF"
grep -E 'sctp' "$CONF"
